url: https://anderssonlab.github.io/PRIMEmodel

template:
  bootstrap: 5
  bootswatch: flatly
  bslib:
    base_font:
      scale: 0.8

navbar:
  left:
    - text: Introduction
      href: articles/installation.html
    - text: Reference
      href: reference/index.html
    - text: Articles
      href: articles/index.html
    - text: PRIME toolkit
      menu:
        - text: PRIMEprep
          href: https://github.com/anderssonlab/PRIMEprep
        - text: PRIME
          href: https://anderssonlab.github.io/PRIME/
        - text: PRIMEmodel
          href: https://anderssonlab.github.io/PRIMEmodel/